export interface Agent {
  id: string | number
  name: string
  ticker: string
  creator: string
  timeAgo: string
  marketCap: string
  change: string
  image: string
  isPositive: boolean
  description?: string
  status?: 'active' | 'inactive' | 'busy' | 'live' | 'upcoming'
  transactions?: number
  recentActivity?: {
    type: string
    time: string
    details: string
  }[]
  fdv?: string
  price?: string
  timeLeft?: string
  holders?: string
  contractAddress?: string
  deploymentType?: 'api' | 'chat'
  chatUrl?: string
}

export const agents: Agent[] = [
  {
    id: 1,
    name: 'missle toe',
    ticker: 'missletoe',
    creator: '0g3fi8',
    timeAgo: '12m ago',
    marketCap: '$8.6K',
    change: '+33.96%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=missletoe',
    isPositive: true,
    status: 'active',
    transactions: 229507,
    fdv: '$11M',
    price: '$0.0042',
  },
  {
    id: 2,
    name: 'Weird Self-introduction',
    ticker: 'WSI',
    creator: 'GtXp8U',
    timeAgo: '3h ago',
    marketCap: '$75.9K',
    change: '+21.98%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=wsi',
    isPositive: true,
    status: 'busy',
    transactions: 15420,
    fdv: '$2.5M',
    price: '$0.012',
  },
  {
    id: 3,
    name: 'Big Morning Energy',
    ticker: 'GM',
    creator: '3jgeH4',
    timeAgo: '3h ago',
    marketCap: '$217.3K',
    change: '-4.60%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=gm',
    isPositive: false,
    status: 'active',
    transactions: 8900,
    fdv: '$500K',
    price: '$0.089',
  },
  {
    id: 4,
    name: 'Retardrick',
    ticker: 'RETARDRICK',
    creator: 'HcP9c2',
    timeAgo: '41m ago',
    marketCap: '$74.2K',
    change: '+9.26%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=retardrick',
    isPositive: true,
    status: 'active',
    transactions: 45000,
    fdv: '$1.2M',
    price: '$0.003',
  },
  {
    id: 5,
    name: 'bert',
    ticker: 'bert',
    creator: 'AF9JYx',
    timeAgo: '1h ago',
    marketCap: '$18.2K',
    change: '-39.48%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=bert',
    isPositive: false,
    description: 'this is bert',
    status: 'inactive',
    transactions: 1200,
    fdv: '$50K',
    price: '$0.0001',
  },
  {
    id: 6,
    name: 'the NIMBUS project',
    ticker: 'NIMBUS',
    creator: 'Bia8Zk',
    timeAgo: '10m ago',
    marketCap: '$5.3K',
    change: '+4.96%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=nimbus',
    isPositive: true,
    description: 'WELCOME TO THE NIMBUS PROJECT!!! DEX ON BOND BABY!! LETS RUN IT',
    status: 'active',
    transactions: 3400,
    fdv: '$150K',
    price: '$0.005',
  },
  {
    id: 7,
    name: 'Graphista by pippin',
    ticker: 'Graphista',
    creator: 'HD7ywG',
    timeAgo: '2h ago',
    marketCap: '$15.0K',
    change: '-11.45%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=graphista',
    isPositive: false,
    status: 'busy',
    transactions: 6700,
    fdv: '$300K',
    price: '$0.009',
  },
  {
    id: 8,
    name: 'Elmo',
    ticker: 'Elmo',
    creator: 'FhkSjG',
    timeAgo: '47m ago',
    marketCap: '$14.8K',
    change: '+35.82%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=elmo',
    isPositive: true,
    description: "Elmo's world",
    status: 'active',
    transactions: 9800,
    fdv: '$400K',
    price: '$0.015',
  },
  {
    id: 9,
    name: '吉祥马',
    ticker: '吉祥马',
    creator: '8jMeYk',
    timeAgo: '37m ago',
    marketCap: '$15.4K',
    change: '+32.28%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=lucky',
    isPositive: true,
    description: '春晚吉祥物 吉祥马',
    status: 'active',
    transactions: 11200,
    fdv: '$450K',
    price: '$0.022',
  },
  {
    id: 10,
    name: 'ShitForFuckingPoorPeople',
    ticker: 'SFFPP',
    creator: '9eEfqP',
    timeAgo: '1h ago',
    marketCap: '$12.7K',
    change: '-11.43%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=sffpp',
    isPositive: false,
    status: 'inactive',
    transactions: 500,
    fdv: '$20K',
    price: '$0.0005',
  },
  {
    id: 11,
    name: 'Poop Fart Piss Jar',
    ticker: 'PFPJ',
    creator: '9YY8qq',
    timeAgo: '2h ago',
    marketCap: '$10.7K',
    change: '-7.73%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=pfpj',
    isPositive: false,
    description: 'Everyone knows the main runner should be on pumpfun',
    status: 'busy',
    transactions: 800,
    fdv: '$30K',
    price: '$0.0008',
  },
  {
    id: 12,
    name: 'fug',
    ticker: 'fug',
    creator: '7a85qic',
    timeAgo: '2d ago',
    marketCap: '$11.8K',
    change: '+35.17%',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=fug',
    isPositive: true,
    status: 'active',
    transactions: 5600,
    fdv: '$250K',
    price: '$0.006',
  },
  // Trending Agents
  {
    id: 13,
    name: 'Luna',
    ticker: 'LUNA',
    creator: 'System',
    timeAgo: '1d ago',
    marketCap: '$12M',
    change: '+12.5%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna',
    isPositive: true,
    price: '$1.24',
    status: 'active',
    holders: '1,234',
    contractAddress: '0x1234...5678',
  },
  {
    id: 14,
    name: 'Kaito',
    ticker: 'KAITO',
    creator: 'System',
    timeAgo: '2d ago',
    marketCap: '$8.5M',
    change: '-2.3%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kaito',
    isPositive: false,
    price: '$0.85',
    status: 'active',
  },
  {
    id: 15,
    name: 'Nova',
    ticker: 'NOVA',
    creator: 'System',
    timeAgo: '5h ago',
    marketCap: '$21M',
    change: '+5.8%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nova',
    isPositive: true,
    price: '$2.10',
    status: 'active',
  },
  {
    id: 16,
    name: 'Atlas',
    ticker: 'ATLS',
    creator: 'System',
    timeAgo: '12h ago',
    marketCap: '$4.5M',
    change: '+32.1%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Atlas',
    isPositive: true,
    price: '$0.45',
    status: 'active',
  },
  // Live Agents
  {
    id: 17,
    name: 'Tyga',
    ticker: 'TYGA',
    creator: 'System',
    timeAgo: 'Live',
    marketCap: '$5M',
    change: '+12.5%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tyga',
    isPositive: true,
    description: 'Tyga is an AI-native intellectual that can solve complex problems...',
    status: 'live',
    timeLeft: '45d 03h 12m',
  },
  {
    id: 18,
    name: 'REPPO',
    ticker: 'REPO',
    creator: 'System',
    timeAgo: 'Upcoming',
    marketCap: '-',
    change: '+8.2%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Reppo',
    isPositive: true,
    description: 'AI TRADING BOT + PREDICTIVE MARKET AI LIVE...',
    status: 'upcoming',
    timeLeft: '01d 12h 30m',
  },
  {
    id: 19,
    name: 'Nuna',
    ticker: 'NUNA',
    creator: 'System',
    timeAgo: 'Upcoming',
    marketCap: '-',
    change: '+24.1%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nuna',
    isPositive: true,
    description: 'Im here just wanna b happyyy <3 wanna see me...',
    status: 'upcoming',
    timeLeft: '03d 05h 10m',
  },
  // Extra from CTA
  {
    id: 20,
    name: 'Kora',
    ticker: 'KORA',
    creator: 'System',
    timeAgo: '1h ago',
    marketCap: '$1M',
    change: '+5.7%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kora',
    isPositive: true,
    status: 'active',
  },
  {
    id: 21,
    name: 'Zen',
    ticker: 'ZEN',
    creator: 'System',
    timeAgo: '2h ago',
    marketCap: '$2M',
    change: '+15.3%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zen',
    isPositive: true,
    status: 'active',
  },
  {
    id: 22,
    name: 'Flux',
    ticker: 'FLUX',
    creator: 'System',
    timeAgo: '3h ago',
    marketCap: '$3M',
    change: '+9.8%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Flux',
    isPositive: true,
    status: 'active',
  },
  {
    id: 23,
    name: 'Echo',
    ticker: 'ECHO',
    creator: 'System',
    timeAgo: '4h ago',
    marketCap: '$4M',
    change: '+3.2%',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Echo',
    isPositive: true,
    status: 'active',
  },
  // Generated Agents
  ...Array.from({ length: 30 }, (_, i) => {
    const id = 24 + i
    const names = [
      'Alpha',
      'Beta',
      'Gamma',
      'Delta',
      'Epsilon',
      'Zeta',
      'Eta',
      'Theta',
      'Iota',
      'Kappa',
      'Lambda',
      'Mu',
      'Nu',
      'Xi',
      'Omicron',
      'Pi',
      'Rho',
      'Sigma',
      'Tau',
      'Upsilon',
      'Phi',
      'Chi',
      'Psi',
      'Omega',
    ]
    const name =
      names[i % names.length] + (i >= names.length ? ` ${Math.floor(i / names.length) + 1}` : '')
    const isPositive = Math.random() > 0.5
    return {
      id,
      name,
      ticker: name.substring(0, 4).toUpperCase(),
      creator: `0x${Math.random().toString(16).substring(2, 8)}`,
      timeAgo: `${Math.floor(Math.random() * 24)}h ago`,
      marketCap: `$${(Math.random() * 10).toFixed(1)}M`,
      change: `${isPositive ? '+' : '-'}${(Math.random() * 50).toFixed(2)}%`,
      image: `https://api.dicebear.com/7.x/bottts/svg?seed=${name}`,
      isPositive,
      status: (Math.random() > 0.7 ? 'busy' : 'active') as 'active' | 'busy',
      transactions: Math.floor(Math.random() * 10000),
      fdv: `$${(Math.random() * 20).toFixed(1)}M`,
      price: `$${(Math.random() * 2).toFixed(4)}`,
    }
  }),
]
