export const ERROR_CODES = {
  API_FETCH_ERROR: "API_FETCH_ERROR",
  INVALID_PARAMS_ERROR: "INVALID_PARAMS_ERROR",
  INVALID_SEARCH_PARAMS_ERROR: "INVALID_SEARCH_PARAMS_ERROR",
  REQ_BODY_ERROR: "REQ_BODY_ERROR",
  CLIENT_ERROR: "CLIENT_ERROR",
  TOKEN_NOT_FOUND_ERROR: "TOKEN_NOT_FOUND_ERROR",
  ADDRESS_NOT_FOUND_ERROR: "ADDRESS_NOT_FOUND_ERROR",
  USER_NOT_FOUND_ERROR: "USER_NOT_FOUND_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
  INVALID_REQUIRED_FIELDS: "INVALID_REQUIRED_FIELDS",
  TOKEN_ALREADY_EXISTS_ERROR: "TOKEN_ALREADY_EXISTS_ERROR",
  TRANSACTION_ERROR: "TRANSACTION_ERROR",
  TRANSACTION_ALREADY_EXISTS_ERROR: "TRANSACTION_ALREADY_EXISTS_ERROR",
};

export const ERROR_MESSAGES = {
  [ERROR_CODES.API_FETCH_ERROR]:
    "Something went wrong while fetching data. Please try again later.",
  [ERROR_CODES.INVALID_PARAMS_ERROR]: "Invalid parameters passed to the url.",
  [ERROR_CODES.INVALID_SEARCH_PARAMS_ERROR]:
    "Invalid parameters passed to the url.",
  [ERROR_CODES.REQ_BODY_ERROR]:
    "Something went wrong while parsing the request body.",
  [ERROR_CODES.TOKEN_NOT_FOUND_ERROR]: "Token not found.",
  [ERROR_CODES.CLIENT_ERROR]:
    "Something went wrong while fetching data on the client. Please try again later.",
  [ERROR_CODES.ADDRESS_NOT_FOUND_ERROR]: "Address not found.",
  [ERROR_CODES.USER_NOT_FOUND_ERROR]: "User not found.",
  [ERROR_CODES.INTERNAL_SERVER_ERROR]:
    "Something went wrong on the server. Please try again later.",
  [ERROR_CODES.UNAUTHORIZED]: "Unauthorized request.",
  [ERROR_CODES.NOT_FOUND]: "Resource not found.",
  [ERROR_CODES.BAD_REQUEST]: "Bad request.",
  [ERROR_CODES.MISSING_REQUIRED_FIELDS]: "Missing required fields.",
  [ERROR_CODES.INVALID_REQUIRED_FIELDS]: "Invalid required fields.",
  [ERROR_CODES.TOKEN_ALREADY_EXISTS_ERROR]: "Token already exists.",
  [ERROR_CODES.TRANSACTION_ERROR]: "Transaction error.",
  [ERROR_CODES.TRANSACTION_ALREADY_EXISTS_ERROR]: "Transaction already exists.",
};
